language: universe
sudo: required
dist: trusty

install:
  - sudo apt-get update
  - sudo apt-get -y --force-yes install linux-headers-`uname -r`
  - sudo apt-get install -y vagrant


script:
  - packer build travis.json
