language: universe
sudo: required
dist: trusty

install:
  - echo "deb http://download.virtualbox.org/virtualbox/debian trusty contrib" | sudo tee -a /etc/apt/sources.list
  - wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get -y --force-yes install linux-headers-`uname -r`
  - sudo apt-get install -y vagrant virtualbox virtualbox-dkms

script:
  - packer build -debug mans-CentOS-7-x86_64.json
