language: universe
sudo: required
dist: trusty

install:
  - sudo apt-get update
  - sudo apt-get -y --force-yes install linux-headers-`uname -r`
  - sudo apt-get install -y vagrant qemu-system-x86 qemu-kvm


script:
  - travis_wait 999 packer build -machine-readable travis.json
